name: Fretec Deploy

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Versao
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Download Wrapper
        uses: mvn -N io.takari:maven:wrapper -Dmaven=3.9.9

      - name: Build Projeto
        uses: mvn clean install -Dmaven.test.skip

      - name: Dockerhub Integration
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Imagem
        uses: docker build -t mrspock182/login:latest .

      - name: Deploy Dockerhub
        uses: docker push mrspock182/login:latest