name: Fretec Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Versao
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

#      - name: SonarCloud Setup
#        uses: SonarSource/sonarcloud-github-action@v2
#        with:
#          organization: FATEC-Multiplataforma
#          token: ${{ secrets.SONAR_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=FATEC-Multiplataforma_login
            -Dsonar.organization=FATEC-Multiplataforma
            -Dsonar.host.url=https://sonarcloud.io
            -Dmaven.test.skip=true

#      - name: SonarCloud Setup
#        uses: SonarSource/sonarcloud-github-action@v2
#        with:
#          organization: mrspock182
#          token: ${{ secrets.SONAR_TOKEN }}
#
#      - name: SonarCloud Scan
#        run: mvn verify sonar:sonar -Dsonar.projectKey=mrspock182_FATEC-Multiplataforma_login \
#          -Dsonar.organization=mrspock182 \
#          -Dsonar.host.url=https://sonarcloud.io \
#          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


#      - name: Download Wrapper
#        run: mvn -N io.takari:maven:wrapper -Dmaven=3.9.9
#
#      - name: Build Projeto
#        run: mvn clean install -Dmaven.test.skip
#
#      - name: Dockerhub Integration
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build Imagem
#        run: docker build -t mrspock182/login:latest .
#
#      - name: Deploy Dockerhub
#        run: docker push mrspock182/login:latest
