name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Instalar wrapper do Maven
        run: mvn -N io.takari:maven:wrapper -Dmaven=3.9.9

      - name: Build do projeto com Maven
        run: mvn clean install -Dmaven.test.skip

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: docker build -t mrspock182/login:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push mrspock182/login:latest
